name: Changelog

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Latest release tag
        id: tag-version
        run: echo ::set-output name=latest-tag::$(git describe --tags --match 'v*' --abbrev=0)
        
      - name: Display tag version
        run: echo "Latest tag is ${{ steps.tag-version.outputs.latest-tag }}"
    # run: git log {{github.}}.. --pretty='format: %H %s <%as>'
    # - run: echo {{github.ref}}
        
        
