name: Changelog

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Latest release tag
        id: tag-version
        run: echo ::set-output name=latest-tag::$(git describe --tags --match 'v*' --abbrev=0)
        
      - name: Get new commit list
        id: commits
        run: echo ::set-output name=list::$(git log --pretty='tformat:%H %s\\n' ${{ steps.tag-version.outputs.latest-tag }}..)

      - name: Display commit list
        run: echo ${{ steps.commits.outputs.list}}

    # run: git log {{github.}}.. --pretty='format: %H %s <%as>'
    # - run: echo {{github.ref}}
        
        
